language: csharp
mono: none
dist: xenial
dotnet: 3.1
solution: ZabbixSender.Async.sln

env:
  - COVERALLS_REPO_TOKEN=zmU2UBHinK2yNIl7bA56pSRSGvkpc9v55

install:
  - dotnet tool install coveralls.net --tool-path tools
  
script:
  - dotnet test tests  -l "trx;LogFileName=test-results.trx" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:ExcludeByFile=\"**/tests/*.cs\"
  - REPO_COMMIT_AUTHOR=$(git show -s --pretty=format:"%cn")
  - REPO_COMMIT_AUTHOR_EMAIL=$(git show -s --pretty=format:"%ce")
  - REPO_COMMIT_MESSAGE=$(git show -s --pretty=format:"%s")
  - ./tools/csmacnz.Coveralls --opencover -i tests/coverage.opencover.xml --useRelativePaths --commitId $TRAVIS_COMMIT --commitBranch $TRAVIS_BRANCH --jobId $TRAVIS_JOB_ID --serviceName travis-ci --commitAuthor "$REPO_COMMIT_AUTHOR" --commitEmail "$REPO_COMMIT_AUTHOR_EMAIL" --commitMessage "$REPO_COMMIT_MESSAGE"
